=== idia-astro/iDaVIE/Assets/Resources/DataMaps/mapping_schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "definitions": {
    "ColorMap": {
      "enum": [
        "Accent",
        "Afmhot",
        "Autumn",
        "Binary",
        "Blues",
        "Bone",
        "BrBg",
        "Brg",
        "BuGn",
        "BuPu",
        "Bwr",
        "CmRmap",
        "Cool",
        "Coolwarm",
        "Copper",
        "Cubehelix",
        "Dark2",
        "Flag",
        "GistEarth",
        "GistGray",
        "GistHeat",
        "GistNcar",
        "GistRainbow",
        "GistStern",
        "GistYarg",
        "GnBu",
        "Gnuplot",
        "Gnuplot2",
        "Gray",
        "Greens",
        "Greys",
        "Hot",
        "Hsv",
        "Inferno",
        "Jet",
        "Magma",
        "NipySpectral",
        "Ocean",
        "Oranges",
        "OrRd",
        "Paired",
        "Pastel1",
        "Pastel2",
        "Pink",
        "PiYg",
        "Plasma",
        "PrGn",
        "Prism",
        "PuBu",
        "PuBuGn",
        "PuOr",
        "PuRd",
        "Purples",
        "Rainbow",
        "RdBu",
        "RdGy",
        "RdPu",
        "RdYlBu",
        "RdYlGn",
        "Reds",
        "Seismic",
        "Set1",
        "Set2",
        "Set3",
        "Spectral",
        "Spring",
        "Summer",
        "Tab10",
        "Tab20",
        "Tab20B",
        "Tab20C",
        "Terrain",
        "Viridis",
        "Winter",
        "Wistia",
        "YlGn",
        "YlGnBu",
        "YlOrBr",
        "YlOrRd"
      ],
      "type": "string"
    },
    "RenderType": {
      "enum": [
        "Billboard",
        "Line"
      ],
      "type": "string"
    },
    "ScalingType": {
      "enum": [
        "Linear",
        "Log",
        "Sqrt",
        "Squared",
        "Exp"
      ],
      "type": "string"
    },
    "MapFloatEntry": {
      "properties": {
        "Clamped": {
          "type": "boolean"
        },
        "MinVal": {
          "type": "number"
        },
        "MaxVal": {
          "type": "number"
        },
        "Offset": {
          "type": "number"
        },
        "Scale": {
          "type": "number"
        },
        "ScalingType": {
          "$ref": "#/definitions/ScalingType"
        },
        "Source": {
          "type": "string"
        }
      },
      "required": [
        "Source"
      ],
      "type": "object"
    },
    "MappingUniforms": {
      "type": "object",
      "properties": {
        "ColorString": {
          "type": "string",
          "pattern": "^#([a-fA-F0-9]{6}|[a-fA-F0-9]{3})$",
          "example": "#aa33cc"
        },
        "Scale": {
          "type": "number"
        },
        "PointSize": {
          "type": "number"
        },
        "Opacity": {
          "type": "number"
        }
      },
      "additionalProperties": false
    }
  },
  "properties": {
    "ColorMap": {
      "$ref": "#/definitions/ColorMap"
    },
    "Spherical": {
      "type": "boolean"
    },
    "RenderType": {
      "$ref": "#/definitions/RenderType"
    },
    "UniformColor": {
      "type": "boolean"
    },
    "UniformPointSize": {
      "type": "boolean"
    },
    "UniformOpacity": {
      "type": "boolean"
    },
    "Uniforms": {
      "$ref": "#/definitions/MappingUniforms"
    },
    "Mapping": {
      "properties": {
        "X": {
          "$ref": "#/definitions/MapFloatEntry"
        },
        "Y": {
          "$ref": "#/definitions/MapFloatEntry"
        },
        "Z": {
          "$ref": "#/definitions/MapFloatEntry"
        },
        "X2": {
          "$ref": "#/definitions/MapFloatEntry"
        },
        "Y2": {
          "$ref": "#/definitions/MapFloatEntry"
        },
        "Z2": {
          "$ref": "#/definitions/MapFloatEntry"
        },
        "Lat": {
          "$ref": "#/definitions/MapFloatEntry"
        },
        "Lng": {
          "$ref": "#/definitions/MapFloatEntry"
        },
        "R": {
          "$ref": "#/definitions/MapFloatEntry"
        },
        "PointSize": {
          "$ref": "#/definitions/MapFloatEntry"
        },
        "Cmap": {
          "$ref": "#/definitions/MapFloatEntry"
        },
        "Opacity": {
          "$ref": "#/definitions/MapFloatEntry"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "metaMapping": {
      "properties": {
        "Name": {
          "properties": {
            "Source": {
              "type": "string"
            }
          },
          "additionalProperties": false,
          "required": [
            "Source"
          ],
          "type": "object"
        }
      },
      "additionalProperties": false,
      "type": "object"
    }
  },
  "additionalProperties": false,
  "required": [
    "Mapping"
  ],
  "type": "object"
}

=== idia-astro/iDaVIE/Data/SampleData/test_catalog.fits.json
{
  "ColorMap": "Plasma",
  "RenderType": "Line",
  "UniformOpacity": false,
  "UniformPointSize": true,
  "Uniforms": {
    "Scale": 0.001,
    "PointSize": 0.1,
    "Opacity": 0.4,
    "ColorString": "#FFFFFF"
  },
  "Mapping": {
    "Cmap": {
      "Source": "Weight"
    },
    "Opacity": {
      "Source": "Weight",
      "Clamped": true,
      "MinVal": 0.1,
      "MaxVal": 1.0,
      "Scale": 1
    },
    "X": {
      "Source": "X1"
    },
    "Y": {
      "Source": "Y1"
    },
    "Z": {
      "Source": "Z1"
    },
    "X2": {
      "Source": "X2"
    },
    "Y2": {
      "Source": "Y2"
    },
    "Z2": {
      "Source": "Z2"
    }
  }
}
